name: "Tests"

on:
  pull_request:
  workflow_dispatch:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 10 * * 1"

jobs:
  test85:
    name: "Tests PHP 8.5"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.5"

  test84:
    name: "Tests PHP 8.4"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.4"

  test83:
    name: "Tests PHP 8.3"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.3"

  test82:
    name: "Tests PHP 8.2"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.2"

  test81:
    name: "Tests PHP 8.1"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.1"

  testlower:
    name: "Tests PHP 8.1 lowest"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.1"
      composer: "composer update --no-interaction --no-progress --prefer-dist --prefer-stable --prefer-lowest"
